batch_size: 4
filepath: H:/My Documents/Backgrounds
external_stylesheets : [options/style_sheet.css]

visual_aa : [[3, 128, 7, 4, 4], [128, 32, 5, 3, 2], [32, 8, 3, 2, 2]]

visual_aa_args :
    in_size : [512, 512]
    in_channels : 3
    dropout : True
    dropout_val : 0.5

save_path : ckpts/

epoch_num : 1

n_clusters : 8

lll_neighbors : 20

lll_iter : 250
