batch_size: 4
filepath: H:/My Documents/Backgrounds
external_stylesheets : [options/style_sheet.css]

visual_aa : [[3, 256, 7, 4, 4], [256, 128, 5, 3, 2], [128, 64, 3, 2, 2]]

variational : False

visual_aa_args :
    in_size : [512, 512]
    in_channels : 3
    dropout : True
    dropout_val : 0.5
    latent_dim : 1024
    
beta : 0.01
save_path : ckpts/

epoch_num : 1

n_clusters : 8

lll_neighbors : 20

lll_iter : 250

regularize : True

reg_penalty : 0.0001

reg_norm : 2
