batch_size: 1
filepath: H:/My Documents/Backgrounds/
external_stylesheets : [options/style_sheet.css]

visual_aa : [[3, 300, 7, 4, 4], [300, 150, 5, 3, 2], [150, 75, 3, 2, 2]]

variational : False

continue_train : True

visual_aa_args :
    in_size : [256, 256]
    in_channels : 3
    dropout : True
    dropout_val : 0.5
    
beta : 0.01
save_path : ckpts/

epoch_num : 100

clip : False

embedding_method : isomap

general_manifold_params :

    n_neighbors : 10
    n_components : 3

   
    
n_clusters : 8
regularize : False

reg_penalty : 0.0001

reg_norm : 2
